export const HOW_TO_USE_MODULES = [
  {
    moduleKey: "dashboard",
    slug: "dashboard",
    titleKey: "howToUseModuleDashboard",
    descriptionKey: "howToUseModuleDashboardDesc",
    icon: "dashboard",
  },
  {
    moduleKey: "brands",
    slug: "brands",
    titleKey: "howToUseModuleBrands",
    descriptionKey: "howToUseModuleBrandsDesc",
    icon: "business",
  },
  {
    moduleKey: "brand_inner_pages",
    slug: "brand-inner-pages",
    titleKey: "howToUseModuleBrandInnerPages",
    descriptionKey: "howToUseModuleBrandInnerPagesDesc",
    icon: "article",
  },
  {
    moduleKey: "brand_unique_pages",
    slug: "brand-unique-pages",
    titleKey: "howToUseModuleBrandUniquePages",
    descriptionKey: "howToUseModuleBrandUniquePagesDesc",
    icon: "web",
  },
  {
    moduleKey: "support_chat",
    slug: "support-chat",
    titleKey: "howToUseModuleSupportChat",
    descriptionKey: "howToUseModuleSupportChatDesc",
    icon: "support_agent",
  },
  {
    moduleKey: "blogs",
    slug: "blogs",
    titleKey: "howToUseModuleBlogs",
    descriptionKey: "howToUseModuleBlogsDesc",
    icon: "rss_feed",
  },
  {
    moduleKey: "blog_categories",
    slug: "blog-categories",
    titleKey: "howToUseModuleBlogCategories",
    descriptionKey: "howToUseModuleBlogCategoriesDesc",
    icon: "category",
  },
  {
    moduleKey: "settings",
    slug: "settings",
    titleKey: "howToUseModuleSettings",
    descriptionKey: "howToUseModuleSettingsDesc",
    icon: "settings",
  },
  {
    moduleKey: "module_settings",
    slug: "module-settings",
    titleKey: "howToUseModuleModuleSettings",
    descriptionKey: "howToUseModuleModuleSettingsDesc",
    icon: "tune",
  },
  {
    moduleKey: "website_settings",
    slug: "website-settings",
    titleKey: "howToUseModuleWebsiteSettings",
    descriptionKey: "howToUseModuleWebsiteSettingsDesc",
    icon: "language",
  },
  {
    moduleKey: "admin_settings",
    slug: "admin-settings",
    titleKey: "howToUseModuleAdminSettings",
    descriptionKey: "howToUseModuleAdminSettingsDesc",
    icon: "manage_accounts",
  },
];